---
- name: Get user input for MAC Address and IP
  ansible.builtin.pause:
    prompt: "Enter the Mac Address and IP address (or leave blank to finish)"
  register: user_data

- name: Process user input
  ansible.builtin.set_fact:
    mac_ip_list: "{{ mac_ip_list + [user_data.user_input] }}"
  when: user_data.user_input | length > 0

- name: Check if we should continue
  ansible.builtin.set_fact:
    should_continue: "{{ user_data.user_input | length > 0 and mac_ip_list | length < max_inputs }}"

- name: Recursive call to collect more input
  ansible.builtin.include_tasks: collect_mac_ip.yml
  when: should_continue
