---
- name: Ensure firewalld is started and enabled
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
  tags:
    - firewalld
    - service

- name: Configure firewall to allow DHCP, HTTP(S), TFTP
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - dhcp
    - tftp
    - dhcpv6-client
    - tftp
    - http
    - https
  tags:
    - firewall
